[package]
name = "idewave-cli"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
readme = "README.md"
keywords = ["wow", "wowcli", "idewave", "wowclient"]
license = "Apache-2.0"
license-file = "LICENCE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
byteorder = "1.4.3"
num-bigint = "0.4.3"
digest = "0.10.3"
regex = "1.5.6"
sha-1 = "0.9.8"
hmac-sha = "0.6.1"
flate2 = "1.0.24"
arc4 = "0.1.0"
yaml-rust = "0.4.5"
tokio = { version = "1", features = ["sync", "net", "io-util", "macros", "time", "rt-multi-thread"] }
bitflags = "1.3.2"